# Generated by Django 3.1.7 on 2021-03-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210312_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NO_TOPIC', help_text='Тема письма', max_length=100)),
                ('email', models.EmailField(help_text='Ваша почта', max_length=254)),
                ('message', models.TextField(help_text='Ваше сообщение', max_length=1000)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=6),
        ),
    ]
