# Generated by Django 3.1.7 on 2021-03-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(default='default.png', upload_to='course_images'),
        ),
    ]
